// <auto-generated />
using AmericasParksApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmericasParksApi.Migrations
{
    [DbContext(typeof(AmericasParksApiContext))]
    partial class AmericasParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AmericasParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnType("longtext");

                    b.Property<string>("DateEstablished")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = "49,071.40 acres",
                            DateEstablished = "1919",
                            Description = "Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes. There are freshwater, estuary, forest, and intertidal habitats.",
                            Location = "Maine",
                            Name = "Acadia",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 2,
                            Area = "8,256.67 acres",
                            DateEstablished = "1988",
                            Description = "The southernmost national park is on three Samoan islands in the South Pacific. It protects coral reefs, rainforests, volcanic mountains, and white beaches. The area is also home to flying foxes, brown boobies, sea turtles, and 900 species of fish.",
                            Location = "American Samoa",
                            Name = "American Samoa",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 3,
                            Area = "76,678.98 acres",
                            DateEstablished = "1971",
                            Description = "This site features more than 2,000 natural sandstone arches, with some of the most popular arches in the park being Delicate Arch, Landscape Arch and Double Arch. Millions of years of erosion have created these structures in a desert climate where the arid ground has life-sustaining biological soil crusts and potholes that serve as natural water-collecting basins. Other geologic formations include stone pinnacles, fins, and balancing rocks.",
                            Location = "Utah",
                            Name = "Arches",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 4,
                            Area = "242,755.94 acres",
                            DateEstablished = "1978",
                            Description = "The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies within the drainage basin of the White River, in southwestern South Dakota. They contain the largest known assemblage of late Eocene and Oligocene mammal fossils. Wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs.",
                            Location = "South Dakota",
                            Name = "Badlands",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 5,
                            Area = "801,163.21 acres",
                            DateEstablished = "1944",
                            Description = "Named for the prominent bend in the Rio Grande along the U.S.–Mexico border, this park encompasses a large and remote part of the Chihuahuan Desert. Its main attraction is backcountry recreation in the arid Chisos Mountains and in canyons along the river. A wide variety of Cretaceous and Tertiary fossils as well as cultural artifacts of Native Americans also exist within its borders.",
                            Location = "Texas",
                            Name = "Big Bend",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 6,
                            Area = "172,971.11 acres",
                            DateEstablished = "1980",
                            Description = "The central part of Biscayne Bay, this mostly underwater park at the north end of the Florida Keys has four interrelated marine ecosystems: mangrove forest, the Bay, the Keys, and coral reefs. Threatened animals include the West Indian manatee, American crocodile, various sea turtles, and the peregrine falcon.",
                            Location = "Florida",
                            Name = "Biscayne",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 7,
                            Area = "30,779.83 acres",
                            DateEstablished = "1999",
                            Description = "The park protects a quarter of the Gunnison River, which slices sheer canyon walls from dark Precambrian-era rock. The canyon features some of the steepest cliffs and oldest rock in North America, and is a popular site for river rafting and rock climbing. The deep, narrow canyon is composed of gneiss and schist, which appears black when in shadow.",
                            Location = "Colorado",
                            Name = "Black Canyon of the Gunnison",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 8,
                            Area = "35,835.08 acres",
                            DateEstablished = "1928",
                            Description = "Bryce Canyon is a geological amphitheater on southern Utah's Paunsaugunt Plateau with hundreds of tall, multicolored sandstone hoodoos formed by erosion. The region was originally settled by Native Americans and later by Mormon pioneers.",
                            Location = "Utah",
                            Name = "Bryce Canyon",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 9,
                            Area = "337,597.83 acres",
                            DateEstablished = "1964",
                            Description = "This landscape was eroded into a maze of canyons, buttes, and mesas by the combined efforts of the Colorado River, Green River, and their tributaries, which divide the park into three districts. The park contains thousands of rock pinnacles and arches, as well as artifacts from Ancient Pueblo peoples.",
                            Location = "Utah",
                            Name = "Canyonlands",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 10,
                            Area = "241,904.50 acres",
                            DateEstablished = "1971",
                            Description = "The park's Waterpocket Fold is a 100-mile (160 km) monocline that exhibits the earth's diverse geologic layers. Other natural features include monoliths, eroded buttes, and sandstone domes, including one shaped like the United States Capitol.",
                            Location = "Utah",
                            Name = "Capitol Reef",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 11,
                            Area = "46,766.45 acres",
                            DateEstablished = "1930",
                            Description = "Carlsbad Caverns has 117 caves, the longest of which is over 120 miles (190 km) long. The Big Room is almost 4,000 feet (1,200 m) long, and the caves are home to over 400,000 Mexican free-tailed bats and sixteen other species. Above ground are the Chihuahuan Desert and Rattlesnake Springs.",
                            Location = "New Mexico",
                            Name = "Carlsbad Caverns ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 12,
                            Area = "249,561.00 acres",
                            DateEstablished = "1980",
                            Description = "Five of the eight Channel Islands are protected, with half of the park's area underwater. The islands have a unique Mediterranean ecosystem originally settled by the Chumash people. They are home to over 2,000 species of land plants and animals, 145 endemic to them, including the island fox. Ferry services offer transportation to the islands from the mainland.",
                            Location = "California",
                            Name = "Channel Islands",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 13,
                            Area = "26,692.60 acres",
                            DateEstablished = "2003",
                            Description = "On the Congaree River, this park is the largest portion of old-growth floodplain forest left in North America. Some of the trees are the tallest in the eastern United States. An elevated walkway called the Boardwalk Loop guides visitors through the swamp.",
                            Location = "South Carolina",
                            Name = "Congaree",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 14,
                            Area = "183,224.05 acres",
                            DateEstablished = "1902",
                            Description = "Crater Lake lies in the caldera of an ancient volcano called Mount Mazama that collapsed 7,700 years ago. The lake is the deepest in the United States and is noted for its vivid blue color and water clarity. Wizard Island and the Phantom Ship are more recent volcanic formations within the caldera. As the lake has no inlets or outlets, it is replenished only by precipitation.",
                            Location = "Oregon",
                            Name = "Crater Lake",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 15,
                            Area = "32,571.89 acres",
                            DateEstablished = "2000",
                            Description = "This park along the Cuyahoga River has waterfalls, hills, trails, and exhibits on early rural living. The Ohio and Erie Canal Towpath Trail follows the Ohio and Erie Canal, where mules towed canal boats. The park has numerous historic homes, bridges, and structures, and also offers a scenic train ride.",
                            Location = "Ohio",
                            Name = "Cuyahoga Valley",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 16,
                            Area = "3,408,395.63 acres",
                            DateEstablished = "1994",
                            Description = "Death Valley is the hottest, lowest, and driest place in the United States, with daytime temperatures that have exceeded 130 °F (54 °C). The park protects Badwater Basin and its vast salt flats at the lowest elevation in North America, −282 ft (−86 m),This geologic graben also protects numerous canyons, badlands, sand dunes, mountain ranges, historic mines, springs, and more than 1,000 species of plants that grow.",
                            Location = "California, Nevada",
                            Name = "Death Valley",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 17,
                            Area = "4,740,911.16 acres",
                            DateEstablished = "1917",
                            Description = "Centered on Denali, the tallest and most prominent mountain in North America, the park is serviced by a single road leading to Wonder Lake, most of which can only be accessed via scheduled tour buses. Denali and other peaks of the Alaska Range are covered with long glaciers and boreal forest. Wildlife includes grizzly bears, Dall sheep, moose, caribou, and wolves.",
                            Location = "Alaska",
                            Name = "Denali",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 18,
                            Area = "64,701.22 acres",
                            DateEstablished = "1992",
                            Description = "The islands of the Dry Tortugas, at the westernmost end of the Florida Keys, are the site of Fort Jefferson, a Civil War-era fort that is the largest masonry structure in the Western Hemisphere. The park is home to undisturbed coral reefs and shipwrecks, and is only accessible by plane or boat.",
                            Location = "Florida",
                            Name = "Dry Tortugas",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 19,
                            Area = "1,508,938.57 acres",
                            DateEstablished = "1934",
                            Description = "The Everglades are the largest tropical wilderness in the United States. This mangrove and tropical rainforest ecosystem and marine estuary is home to 36 protected species, including the Florida panther, American crocodile, and West Indian manatee. Some areas have been drained and developed; restoration projects aim to restore the ecology.",
                            Location = "Florida",
                            Name = "Everglades",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 20,
                            Area = "7,523,897.45 acres",
                            DateEstablished = "1980",
                            Description = "The country's northernmost park protects an expanse of pure wilderness in Alaska's Brooks Range and has no park facilities. The land is home to Alaska Natives who have relied on the land and caribou for 11,000 years.",
                            Location = "Alaska",
                            Name = "Gates of the Arctic",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 21,
                            Area = "192.83 acres",
                            DateEstablished = "2018",
                            Description = "The Gateway Arch is a 630-foot (192 m) (both high and wide) catenary arch built in the 1960s to commemorate the Lewis and Clark Expedition, initiated by Thomas Jefferson, and the subsequent westward expansion of the country. The nearby Old Courthouse, across a greenway to the west of the arch, was the original site of the landmark Dred Scott case about slavery. An underground museum describes the arch's construction and the country's westward expansion.",
                            Location = "Missouri",
                            Name = "Gateway Arch",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 22,
                            Area = "1,013,126.39 acres",
                            DateEstablished = "1910",
                            Description = "The U.S. half of Waterton-Glacier International Peace Park, this park includes 26 rapidly receding glaciers and 130 named lakes surrounded by Rocky Mountain peaks. Historic hotels and the landmark Going-to-the-Sun Road accommodate visitors. The local mountains, formed by an overthrust, expose Paleozoic fossils including trilobites, mollusks, giant ferns and dinosaurs. The park is also home to Triple Divide Peak, which forms the boundary between the watersheds of the Atlantic, Pacific, and Arctic Oceans.",
                            Location = "Montana",
                            Name = "Glacier",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 23,
                            Area = "3,223,383.43 acres",
                            DateEstablished = "1980",
                            Description = "Glacier Bay contains tidewater glaciers, mountains, fjords, and a temperate rainforest, and is home to large populations of grizzly bears, mountain goats, whales, seals, and eagles. When discovered in 1794 by George Vancouver, the entire bay was covered by ice, but the glaciers have since receded more than 65 miles (105 km).",
                            Location = "Alaska",
                            Name = "Glacier Bay",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 24,
                            Area = "1,201,647.03 acres",
                            DateEstablished = "1919",
                            Description = "The Grand Canyon, carved by the mighty Colorado River, is 277 miles (446 km) long, up to 1 mile (1.6 km) deep, and up to 15 miles (24 km) wide. Millions of years of erosion have resulted in a massive three-tiered canyon, exposing the multicolored layers of the Colorado Plateau in mesas and canyon walls, visible from trails that descend into the canyon from the north and south rims.",
                            Location = "Arizona",
                            Name = "Grand Canyon ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 25,
                            Area = "310,044.36 acres",
                            DateEstablished = "1929",
                            Description = "Grand Teton is the tallest mountain in the scenic Teton Range. The park's historic Jackson Hole and reflective piedmont lakes teem with endemic wildlife, with a backdrop of craggy mountains that rise abruptly from the sage-covered valley below.",
                            Location = "Wyoming",
                            Name = "Grand Teton",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 26,
                            Area = "77,180.00 acres",
                            DateEstablished = "1986",
                            Description = "Based around Nevada's second tallest mountain, Wheeler Peak, Great Basin National Park protects 5,000-year-old bristlecone pines, a rock glacier, and the limestone Lehman Caves. Due to its remote location, the park is home to some of the country's darkest night skies. Wildlife includes the Townsend's big-eared bat, pronghorn, and Bonneville cutthroat trout.",
                            Location = "Nevada",
                            Name = "Great Basin",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 27,
                            Area = "107,345.73 acres",
                            DateEstablished = "2004",
                            Description = "The tallest sand dunes in North America, up to 750 feet (230 m) tall, were formed by deposits of the ancient Rio Grande in the San Luis Valley. Abutting a variety of grasslands, shrublands, and wetlands, the park also features alpine lakes, six 13,000-foot mountains, and old-growth forests.",
                            Location = "Colorado",
                            Name = "Great Sand Dunes",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 28,
                            Area = "522,426.88 acres",
                            DateEstablished = "1934",
                            Description = "The Great Smoky Mountains, part of the Appalachian Mountains, span a wide range of elevations, making them home to over 400 vertebrate species, 100 tree species, and 5,000 plant species. Hiking is the park's main attraction, with over 800 miles (1,300 km) of trails, including 70 miles (110 km) of the Appalachian Trail. Other activities include fishing, horseback riding, and touring nearly 80 historic structures.",
                            Location = "North Carolina, Tennessee",
                            Name = "Great Smoky Mountains",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 29,
                            Area = "86,367.10 acres",
                            DateEstablished = "1972",
                            Description = "This park contains Guadalupe Peak, the highest point in Texas, as well as the scenic McKittrick Canyon filled with bigtooth maples, a corner of the arid Chihuahuan Desert, and a fossilized coral reef from the Permian era.",
                            Location = "Texas",
                            Name = "Guadalupe Mountains",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 30,
                            Area = "33,488.98 acres",
                            DateEstablished = "1961",
                            Description = "The Haleakalā volcano on Maui features a very large crater with numerous cinder cones, a grove of non-native trees, the Kipahulu section's scenic pools of freshwater fish, and the endemic Hawaiian goose. The park protects the greatest number of endangered species within a U.S. national park.",
                            Location = "Hawaii",
                            Name = "Haleakalā",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 31,
                            Area = "344,812.18 acres",
                            DateEstablished = "1916",
                            Description = "This park on the Big Island protects the Kīlauea and Mauna Loa volcanoes, two of the world's most active geological features. Diverse ecosystems range from tropical forests at sea level to barren lava beds at more than 13,000 feet (4,000 m).",
                            Location = "Hawaii",
                            Name = "Hawaiʻi Volcanoes",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 32,
                            Area = "5,554.15 acres",
                            DateEstablished = "1921",
                            Description = "Hot Springs was originally established by Congress as a federal reserve on April 20, 1832, making it the oldest area managed by the National Park Service. Natural thermal springs flow out of the Ouachita Mountains, providing opportunities for relaxation in a historic setting. Bathhouse Row preserves examples of 19th-century architecture. Hot Springs is the first national park within a city and was the smallest national park until 2018.",
                            Location = "Arkansas",
                            Name = "Hot Springs",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 33,
                            Area = "15,349.08 acres",
                            DateEstablished = "2019",
                            Description = "Previously designated a national lakeshore, parts of this 20-mile (32 km) stretch of the southern shore of Lake Michigan have sandy beaches and tall dunes. The park includes grassy prairies, peat bogs, and marsh wetlands home to over 2,000 species.",
                            Location = "Indiana",
                            Name = "Indiana Dunes",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 34,
                            Area = "571,790.30 acres",
                            DateEstablished = "1940",
                            Description = "The largest island in Lake Superior is a place of isolation and wilderness. Along with its many shipwrecks, waterways, and hiking trails, the park also includes over 400 smaller islands within 4.5 miles (7.2 km) of its shores. There are only 20 mammal species on the island, though the relationship between its wolf and moose populations is especially unique.",
                            Location = "Michigan",
                            Name = "Isle Royale",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 35,
                            Area = "795,155.85 acres",
                            DateEstablished = "1994",
                            Description = "Covering large areas of the Colorado and Mojave Deserts and the Little San Bernardino Mountains, this desert landscape is populated by vast stands of Joshua trees. Large changes in elevation reveal various contrasting environments including bleached sand dunes, dry lakes, rugged mountains, and maze-like clusters of monzogranite monoliths.",
                            Location = "California",
                            Name = "Joshua Tree",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 36,
                            Area = "3,674,529.33 acres",
                            DateEstablished = "1980",
                            Description = "This park on the Alaska Peninsula protects the Valley of Ten Thousand Smokes, an ash flow formed by the 1912 eruption of Novarupta, and the stratovolcano Mount Katmai. Over 2,000 grizzly bears come here each year to catch spawning salmon. Other wildlife includes caribou, wolves, moose, and wolverines.",
                            Location = "Alaska",
                            Name = "Katmai",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 37,
                            Area = "669,650.05 acres",
                            DateEstablished = "1980",
                            Description = "Near Seward on the Kenai Peninsula, this park protects the Harding Icefield and at least 38 glaciers and fjords stemming from it. The only area accessible to the public by road is the rapidly shrinking Exit Glacier. Boat and kayak tours offer views of tidewater glaciers, whales, sea lions, and marine birds.",
                            Location = "Alaska",
                            Name = "Kenai Fjords",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 38,
                            Area = "461,901.20 acres",
                            DateEstablished = "1940",
                            Description = "Home to several giant sequoia groves and the General Grant Tree, the world's second largest measured tree, this park also features part of the Kings River, sculptor of the dramatic granite canyon that is its namesake, and the San Joaquin River, as well as Boyden Cave. Although Kings Canyon National Park was designated as such in 1940, it subsumed General Grant National Park, which had been established on October 1, 1890, as the United States' fourth national park.",
                            Location = "California",
                            Name = "Kings Canyon",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 39,
                            Area = "1,750,716.16 acres",
                            DateEstablished = "1980",
                            Description = "Kobuk Valley protects 61 miles (98 km) of the Kobuk River and three regions of sand dunes. Created by glaciers, the Great Kobuk, Little Kobuk, and Hunt River Sand Dunes can reach 100 feet (30 m) high and 100 °F (38 °C), and they are the largest dunes in the Arctic. Twice a year, half a million caribou migrate through the dunes and across river bluffs that expose well-preserved ice age fossils.",
                            Location = "Alaska",
                            Name = "Kobuk Valley",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 40,
                            Area = "2,619,816.49 acres",
                            DateEstablished = "1980",
                            Description = "The region around Lake Clark features four active volcanoes, including Mount Redoubt, as well as an abundance of rivers, glaciers, and waterfalls. Temperate rainforests, a tundra plateau, and three mountain ranges complete the landscape.",
                            Location = "Alaska",
                            Name = "Lake Clark",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 41,
                            Area = "106,589.02 acres",
                            DateEstablished = "1916",
                            Description = "Lassen Peak, the largest lava dome volcano in the world, is joined by all three other types of volcanoes in this park: shield, cinder cone, and composite. Though Lassen itself last erupted in 1915, most of the rest of the park is continuously active. Numerous hydrothermal features, including fumaroles, boiling pools, and bubbling mud pots, are heated by molten rock from beneath the peak.",
                            Location = "California",
                            Name = "Lassen Volcanic",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 42,
                            Area = "72,472.87 acres",
                            DateEstablished = "1941",
                            Description = "With more than 400 miles (640 km) of passageways explored, Mammoth Cave is the world's longest known cave system. Subterranean wildlife includes eight bat species, Kentucky cave shrimp, Northern cavefish, and cave salamanders. Above ground, the park provides recreation on the Green River, 70 miles of hiking trails, and plenty of sinkholes and springs.",
                            Location = "Kentucky",
                            Name = "Mammoth Cave",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 43,
                            Area = "52,485.17 acres",
                            DateEstablished = "1906",
                            Description = "This area constitutes over 4,000 archaeological sites of the Ancestral Puebloan people, who lived here and elsewhere in the Four Corners region for at least 700 years. Cliff dwellings built in the 12th and 13th centuries include Cliff Palace, which has 150 rooms and 23 kivas, and the Balcony House, with its many passages and tunnels.",
                            Location = "Colorado",
                            Name = "Mesa Verde ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 44,
                            Area = "236,381.64 acres",
                            DateEstablished = "1899",
                            Description = "Mount Rainier, an active stratovolcano, is the most prominent peak in the Cascades and is covered by 26 named glaciers including Carbon Glacier and Emmons Glacier, the longest and largest in the contiguous United States respectively. The mountain is popular for climbing, and more than half of the park is covered by subalpine and alpine forests and meadows seasonally in bloom with wildflowers. Paradise on the south slope is among the snowiest places on Earth. The Longmire visitor center is the start of the Wonderland Trail, which encircles the mountain.",
                            Location = "Washington",
                            Name = "Mount Rainier",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 45,
                            Area = "7,021 acres",
                            DateEstablished = "2020",
                            Description = "The New River Gorge is the deepest river gorge east of the Mississippi River. The park primarily covers the lower gorge area around the New River Gorge Bridge, which features some of the country's best whitewater rafting. Smaller noncontiguous sections showcase the ghost town of Thurmond, the scenic Grandview vista, and Sandstone Falls. The other 65,165 acres (263.71 km2) of the redesignated national river is now a national preserve, spanning 53 mi (85 km) of the New River.",
                            Location = "West Virginia",
                            Name = "New River Gorge",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 46,
                            Area = "504,780.94 acres",
                            DateEstablished = "1968",
                            Description = "The highly glaciated mountains of the North Cascades Range exhibit a spectacular and complex geologic history. Between the river valleys and high peaks there are eight diverse life zones with 75 mammal and 1,600 vascular plant species. Popular hiking and climbing areas of the Stephen Mather Wilderness include Cascade Pass, Mount Shuksan, Mount Triumph, and Eldorado Peak. Ross Lake and Lake Chelan National Recreation Areas adjoin the two segments of the park and are all administered together.",
                            Location = "Washington",
                            Name = "North Cascades",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 47,
                            Area = "922,649.41 acres",
                            DateEstablished = "1938",
                            Description = "This park on the Olympic Peninsula includes a wide range of ecosystems from Pacific shoreline to temperate rainforests to the glaciated alpine peaks of the Olympic Mountains, the tallest of which is Mount Olympus. The Hoh and Quinault Rainforests are the wettest areas in the contiguous United States, with the Hoh receiving an average of almost 12 ft (3.7 m) of rain every year.",
                            Location = "Washington",
                            Name = "Olympic",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 48,
                            Area = "221,390.21 acres",
                            DateEstablished = "1962",
                            Description = "This portion of the Chinle Formation has a large concentration of 225-million-year-old petrified wood. The surrounding Painted Desert features eroded cliffs of red-hued volcanic rock called bentonite. Dinosaur fossils and over 350 Native American sites are also protected in this park.",
                            Location = "Arizona",
                            Name = "Petrified Forest",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 49,
                            Area = "26,685.73 acres",
                            DateEstablished = "2013",
                            Description = "Named for the eroded leftovers of a portion of an extinct volcano, the park's massive black and gold monoliths of andesite and rhyolite are a popular destination for rock climbers. Hikers have access to trails crossing the Coast Range wilderness. The park is one of the few locations where the endangered California condor can be seen in the wild. Pinnacles also supports a dense population of prairie falcons and more than 13 species of bat that populate its talus caves.",
                            Location = "California",
                            Name = "Pinnacles",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 50,
                            Area = "138,999.37 acres",
                            DateEstablished = "1968",
                            Description = "This park and the co-managed state parks protect almost half of all remaining coastal redwoods, the tallest trees on earth. There are three large river systems in this very seismically active area, and 37 miles (60 km) of protected coastline reveal tide pools and seastacks. The prairie, estuary, coast, river, and forest ecosystems contain a wide variety of animal and plant species.",
                            Location = "California",
                            Name = "Redwood ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 51,
                            Area = "265,847.74 acres",
                            DateEstablished = "1915",
                            Description = "Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including elk, moose, mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m).",
                            Location = "Colorado",
                            Name = "Rocky Mountain",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 52,
                            Area = "92,876.75 acres",
                            DateEstablished = "1994",
                            Description = "Split into the separate Rincon Mountain and Tucson Mountain districts, this park is evidence that the dry Sonoran Desert is still home to a great variety of life spanning six biotic communities. Beyond the namesake giant saguaro cacti, there are barrel cacti, chollas, and prickly pears, as well as lesser long-nosed bats, spotted owls, and javelinas.",
                            Location = "Arizona",
                            Name = "Saguaro",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 53,
                            Area = "404,062.63 acres",
                            DateEstablished = "1890",
                            Description = "This park protects the Giant Forest, which boasts some of the world's largest trees, the General Sherman being the largest measured tree in the park. Other features include over 240 caves, a long segment of the Sierra Nevada including the tallest mountain in the contiguous United States, and Moro Rock, a large granite dome.",
                            Location = "California",
                            Name = "Sequoia",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 54,
                            Area = "200,445.92 acres",
                            DateEstablished = "1935",
                            Description = "Shenandoah's Blue Ridge Mountains are covered by hardwood forests that teem with a wide variety of wildlife. The Skyline Drive and Appalachian Trail run the entire length of this narrow park, along with more than 500 miles (800 km) of hiking trails passing scenic overlooks and cataracts of the Shenandoah River.",
                            Location = "Virginia",
                            Name = "Shenandoah",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 55,
                            Area = "70,446.89 acres",
                            DateEstablished = "1978",
                            Description = "This region that enticed and influenced President Theodore Roosevelt consists of a park of three units in the northern badlands. Besides Roosevelt's historic cabin, there are numerous scenic drives and backcountry hiking opportunities. Wildlife includes American bison, pronghorn, bighorn sheep, and wild horses.",
                            Location = "North Dakota",
                            Name = "Theodore Roosevelt",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 56,
                            Area = "15,052.33 acres",
                            DateEstablished = "1956",
                            Description = "This island park on Saint John preserves pristine beaches surrounded by mangrove forests, seagrass beds, and coral reefs. It also has Taíno archaeological sites and the ruins of sugar plantations from Columbus's time.",
                            Location = "U.S. Virgin Islands",
                            Name = "Virgin Islands",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 57,
                            Area = "218,222.35 acres",
                            DateEstablished = "1975",
                            Description = "This park protecting four lakes near the Canada–US border is a site for canoeing, kayaking, and fishing. The park also preserves a history populated by Ojibwe Native Americans, French fur traders called voyageurs, and gold miners. Formed by glaciers, the region features tall bluffs, rock gardens, islands, bays, and several historic buildings.",
                            Location = "Minnesota",
                            Name = "Voyageurs",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 58,
                            Area = "146,344.31 acres",
                            DateEstablished = "2019",
                            Description = "Located in the mountain-ringed Tularosa Basin, White Sands consists of the southern part of a 275-square-mile (710 km2) field of white sand dunes composed of gypsum crystals—the world's largest gypsum dunefield. The park is completely within the White Sands Missile Range and is subject to closure when tests are conducted.",
                            Location = "New Mexico",
                            Name = "White Sands",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 59,
                            Area = "33,970.84 acres",
                            DateEstablished = "1903",
                            Description = "Wind Cave is distinctive for its calcite fin formations called boxwork, a unique formation rarely found elsewhere, and needle-like growths called frostwork. It is one of the longest caves in the world and creates a wind as air pressure changes. Above ground is a mixed-grass prairie with animals such as bison, black-footed ferrets, and prairie dogs and ponderosa pine forests home to cougars and elk. The cave is culturally significant to the Lakota people as a creation site.",
                            Location = "South Dakota",
                            Name = "Wind Cave",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 60,
                            Area = "8,323,146.48 acres",
                            DateEstablished = "1980",
                            Description = "The largest national park in the system protects the convergence of the Alaska, Chugach, Wrangell, and Saint Elias Ranges, which include many of the continent's tallest mountains and volcanoes, including the 18,008-foot Mount Saint Elias. More than a quarter of the park is covered with glaciers, including the tidewater Hubbard Glacier, piedmont Malaspina Glacier, and valley Nabesna Glacier.",
                            Location = "Alaska",
                            Name = "Wrangell–St. Elias ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 61,
                            Area = "2,219,790.71 acres",
                            DateEstablished = "1872",
                            Description = "Situated on the Yellowstone Caldera, the park has an expansive network of geothermal areas including boiling mud pots, vividly colored hot springs such as Grand Prismatic Spring, and regularly erupting geysers, the best-known being Old Faithful. The yellow-hued Grand Canyon of the Yellowstone River contains several high waterfalls, and four mountain ranges traverse the park. More than 60 mammal species including timber wolves, grizzly bears, black bears, lynxes, bison, and elk make this park one of the best wildlife viewing spots in the country.",
                            Location = "Wyoming, Montana, Idaho",
                            Name = "Yellowstone",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 62,
                            Area = "761,747.50 acres",
                            DateEstablished = "1890",
                            Description = "Yosemite features sheer granite cliffs, exceptionally tall waterfalls, and old-growth forests at a unique intersection of geology and hydrology. Half Dome and El Capitan rise from the park's centerpiece, the glacier-carved Yosemite Valley, and from its vertical walls drop Yosemite Falls, one of North America's tallest waterfalls at 2,425 feet (739 m) high. Three giant sequoia groves, along with a pristine wilderness in the heart of the Sierra Nevada, are home to a wide variety of rare plant and animal species.",
                            Location = "California",
                            Name = "Yosemite ",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 63,
                            Area = "147,242.66 acres",
                            DateEstablished = "1919",
                            Description = "Located at the junction of the Colorado Plateau, Great Basin, and Mojave Desert, this park contains sandstone features such as mesas, rock towers, and canyons, including the Virgin River Narrows. The various sandstone formations and the forks of the Virgin River create a wilderness divided into four ecosystems: desert, riparian, woodland, and coniferous forest.",
                            Location = "Utah",
                            Name = "Zion",
                            Type = "National Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
